### PR TITLE
Create Character.txt

### PR DESCRIPTION
**Pull request by harmeetsinghjsr**

### CODE REVIEW

**Comment by kartikeysingh6** [comment]
Not a code, doesn't even achieve some objective. Improve yourself.

**Comment by harmeetsinghjsr** [comment]
hello sir, i was unaware of the prs then but i got labeled as invalid can u please remove the label as i want to participate in hacktober fest, i need to get those labels removed there are three of them. please kindly help i would definately improve on this. and promise not to do such things again..

**Comment by kartikeysingh6** [comment]
@harmeetsinghjsr Thank you for your acknowledgement. Have a good day.

**Review by kartikeysingh6 — APPROVED** [review]
Not a code

**Pull request merged**
